### ISSUE TITLE
other segmentation dataset tested or not?

### ISSUE THREAD

**Issue by mrj-taffy** [nachifur/automatic_label_correction_based_CCEDD#4]
hi,  nachifur!  I wanna know that, have you tested other common-used segmentation datasets?  I do research in segmentation, and it's great to use this method on my own dataset.

**Comment by nachifur** [comment]
Thank you very much for your interest in our method.
First, I am very sorry that I did not receive your message in time.

To the best of our knowledge, our LLPC is the first label correction method for edge detection and image segmentation. Our local point correction method is general because it is based on the correction of label points. We test LLPC on our CCEDD, and the correction results for natural images are shown at the end of our [paper](https://www.frontiersin.org/articles/10.3389/fninf.2022.895290/full). 

I am very much looking forward to have a more in-depth communication with you.
